### ISSUE TITLE
You are getting too many stars

### ISSUE THREAD

**Issue by ElDavoo** [octeep/wireproxy#11]
Wtf
![image](https://user-images.githubusercontent.com/7345120/160293878-07a9bd1c-4e20-4d7a-9be1-409ceacbf130.png)

**Comment by octeep** [comment]
Bruh idk either man

**Comment by tensorknower69** [comment]
yeah sorry i rigged it

**Comment by tensorknower69** [comment]
https://github.com/octeep/wireproxy/pull/13

**Comment by MosesBostock11** [comment]
They are bots.🫡

**Comment by ElDavoo** [comment]
> They are bots.🫡

so this means ban from github soon 🥲
