### ISSUE TITLE
Parse subnet after Self/Peer Endpoint

### ISSUE THREAD

**Issue by ElDavoo** [octeep/wireproxy#14]
Addresses like 192.168.1.67/26 will panic the problem with:

`ParseAddr("192.168.1.67/26"): unexpected character (at "/26")`

the subnet should be parsed

**Comment by octeep** [comment]
Yeah this is intentional, because wireproxy doesn't need to take subnets into account. What are you trying to to do?

**Comment by ElDavoo** [comment]
I'm writing a python config converter from wireguard syntax to wireproxy syntax so I'm testing out various stuff.

Yeah that's right it's not needed i didn't think about it

**Comment by octeep** [comment]
> I'm writing a python config converter from wireguard syntax to wireproxy syntax so I'm testing out various stuff.
> 
> Yeah that's right it's not needed i didn't think about it

That's on my todo list as well. If you wouldn't mind, please share it when you've completed it :D

**Comment by ElDavoo** [comment]
Err, I didn't write it for publishing (and not gonna improve it) but [here you go](https://gist.github.com/ElDavoo/f3a736afe581a98608773f31540d323b)
