### ISSUE TITLE
How to run wireproxy silently in the background

### ISSUE THREAD

**Issue by fscarmen** [octeep/wireproxy#19]
I run winproxy with the command ```nohup wireproxy /etc/wireguard/proxy.conf >/dev/null 2>&1 &``` .
I want to run it in Systemd.  There is a  problem. Stuck for a long time, eventually showing timeout.
I think it's caused by windproxy running in the foreground

```
[Unit]
Description=WireProxy for WARP
After=network.target
Wants=network.target
Documentation=https://github.com/octeep/wireproxy

[Service]
Type=forking
ExecStart=/usr/bin/wireproxy /etc/wireguard/proxy.conf
RemainAfterExit=yes
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by octeep** [comment]
I don't use systemd so I can't test this out, but have you tried `Type=simple` instead of `Type=forking`?

**Comment by fscarmen** [comment]
I think it would be best to add parameters to run in the background in next verion. For example 
```
wireproxy /etc/wireguard/proxy.conf -d
```
Thank you!

**Comment by octeep** [comment]
> I think it would be best to add parameters to run in the background in next verion. For example
> 
> ```
> wireproxy /etc/wireguard/proxy.conf -d
> ```
> 
> Thank you!

I'll address this in the first "official" release version of wireproxy. I think after getting feedbacks from different communities, the codebase is mature enough. I'm gonna rework the command line parsing part, add this feature, and bump the version to v1.0

**Comment by fscarmen** [comment]
Glad to hear this exciting news. 
Many WARP users have reported such a need. 
I also hope the parameter to close wireproxy. Now I need to use ```kill -9 $(pgrep -f wireproxy)```, which seems rude and unprofessional.

**Comment by octeep** [comment]
> Glad to hear this exciting news. Many WARP users have reported such a need. I also hope the parameter to close wireproxy. Now I need to use `kill -9 $(pgrep -f wireproxy)`, which seems rude and unprofessional.

How exactly would the parameter closing wireproxy looks like? Would it be something like `wireproxy --close`? I am not sure how that work with multiple instances of wireproxy.

**Comment by fscarmen** [comment]
How abt like screen?

case 1: one session
```
[root@srv21706 ~]# screen -SX a quit
[root@srv21706 ~]# screen -ls
No Sockets found in /var/run/screen/S-root.

[root@srv21706 ~]# screen -USdm a
[root@srv21706 ~]# screen -ls
There is a screen on:
        11609.a (Detached)
1 Socket in /var/run/screen/S-root.

[root@srv21706 ~]# screen -SX a quit
[root@srv21706 ~]# screen -ls
No Sockets found in /var/run/screen/S-root.
```

case 2:  multiple sessions
```
[root@srv21706 ~]# screen -USdm a
[root@srv21706 ~]# screen -USdm a
[root@srv21706 ~]# screen -USdm a
[root@srv21706 ~]# screen -ls
There are screens on:
        12705.a (Detached)
        12676.a (Detached)
        12631.a (Detached)
3 Sockets in /var/run/screen/S-root.

[root@srv21706 ~]# screen -SX 12705 quit
[root@srv21706 ~]# screen -ls
There are screens on:
        12676.a (Detached)
        12631.a (Detached)
2 Sockets in /var/run/screen/S-root.

[root@srv21706 ~]# screen -SX 12631.a quit
[root@srv21706 ~]# screen -ls
There is a screen on:
        12676.a (Detached)
1 Socket in /var/run/screen/S-root.
```

**Comment by octeep** [comment]
Ah, so each instance of wireproxy is named and you can close them by specifying the name of the instance of the wireproxy you want to close. I think we can do that. This also ties in to one of the task in #16 too. I will address this in the future.

**Comment by octeep** [comment]
> I think it would be best to add parameters to run in the background in next verion. For example
> 
> ```
> wireproxy /etc/wireguard/proxy.conf -d
> ```
> 
> Thank you!

Daemon flag has been implemented in the latest commit, note that there is also a slight change to how the path of the configuration is passed to wireproxy as well. I've tested the daemon feature on my OpenBSD and Linux machines. Can you confirm that it works for you as well?

**Comment by octeep** [comment]
@fscarmen also did you manage to get wireproxy working with cloudflare warp? I'm interested in using it as well.

**Comment by ElDavoo** [comment]
> @fscarmen also did you manage to get wireproxy working with cloudflare warp? I'm interested in using it as well.
> 
> Edit: nvm got it working

As a bit of off-topic discussion: I wanted to make it working for torrenting, but doesn't look like it works :( the only thing that is working is HTTP tracker updates

**Comment by fscarmen** [comment]
> Can you confirm that it works for you as well?

Quite practical, now I use ```systemctl restart wgcf``` to restart the warp service to indirectly change the warp ip to unlock Netflix.

**Comment by fscarmen** [comment]
> @fscarmen also did you manage to get wireproxy working with cloudflare warp? I'm interested in using it as well.
> 
> Edit: nvm got it working

Yes.
![image](https://user-images.githubusercontent.com/62703343/160808318-96e1f433-0da6-42a2-bb8e-7220cc18e173.png)

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/62703343/160808280-04edc941-d136-4929-8e6d-45b4c42fb907.png">

**Comment by fscarmen** [comment]
Do you mean by CloudFlare WARP Client for Linux?
https://blog.cloudflare.com/announcing-warp-for-linux-and-proxy-mode

Tonight I will add wireproxy options to the menu.

**Comment by fscarmen** [comment]
> I don't use systemd so I can't test this out, but have you tried `Type=simple` instead of `Type=forking`?

It works. Ths.
'Type=simple' is default, so i remove it.
Now the systemd file content is as follow. ( /usr/lib/systemd/system/wireproxy.service )
```
[Unit]
Description=WireProxy for WARP
After=network.target
Documentation=https://github.com/fscarmen/warp
Documentation=https://github.com/octeep/wireproxy
[Service]
ExecStart=/usr/bin/wireproxy /etc/wireguard/proxy.conf
RemainAfterExit=yes
Restart=always
[Install]
WantedBy=multi-user.target
```

I turn on the WireProxy service by ```systemctl enable --now wireproxy```
turn it off by ```systemctl disable --now wireproxy```
change the warp ip (restart service) by ```systemctl restart wireproxy```

**Comment by octeep** [comment]
> > I don't use systemd so I can't test this out, but have you tried `Type=simple` instead of `Type=forking`?
> 
> It works. Ths. 'Type=simple' is default, so i remove it. Now the systemd file content is as follow. ( /usr/lib/systemd/system/wireproxy.service )
> 
> ```
> [Unit]
> Description=WireProxy for WARP
> After=network.target
> Documentation=https://github.com/fscarmen/warp
> Documentation=https://github.com/octeep/wireproxy
> [Service]
> ExecStart=/usr/bin/wireproxy /etc/wireguard/proxy.conf
> RemainAfterExit=yes
> Restart=always
> [Install]
> WantedBy=multi-user.target
> ```
> 
> I turn on the WireProxy service by `systemctl enable --now wireproxy` turn it off by `systemctl disable --now wireproxy` change the warp ip (restart service) by `systemctl restart wireproxy`

Are you using the latest version? It should be `ExecStart=/usr/bin/wireproxy -c /etc/wireguard/proxy.conf`.

**Comment by fscarmen** [comment]
> Are you using the latest version? It should be `ExecStart=/usr/bin/wireproxy -c /etc/wireguard/proxy.conf`.

Not yet. I fail to cross compile wireproxy in action. The previous version was ok. I guess there is no file: main.go

**Comment by octeep** [comment]
> > Are you using the latest version? It should be `ExecStart=/usr/bin/wireproxy -c /etc/wireguard/proxy.conf`.
> 
> Not yet. I fail to cross compile wireproxy in action. The previous version was ok. I guess there is no file: main.go

Ah yes, you should compile with this command: `go build ./cmd/wireproxy` instead. I will add an instruction in README. Alternatively, you can find it on the Actions tab. I setup a CI to build it for every commits.

**Comment by octeep** [comment]
@fscarmen do you mind moving this conversation to discussion? I don't think it's appropiate to discuss on an issue tracker. https://github.com/octeep/wireproxy/discussions/25
