### ISSUE TITLE
Use 'v' prefix in release tags for pkg.go.dev

### ISSUE THREAD

**Issue by lwhsu** [octeep/wireproxy#29]
Congratulations to 1.0.0 release!  If possible, please add a 'v' prefix in the release tags (e.g. `v1.0.0`) so it will be available on pkg.go.dev [1], which will be a great help for the port of wireproxy for FreeBSD [2], which maintained by me.  It's fine to have multiple tags to the same commit so co-existing of `1.0.0` and `v1.0.0` tags is fine.

The reason we want to download from pkg.go.dev is because that in ports system's design, we download everything required for build in the fetch step, then verify the checksum and build in offline mode.  This is for both security and reproducibility.  The availability on pkg.go.dev means that we can get the dependency information from go.mod there and then fetch all the build requirements before actually build it. [3]

Please help this so I can update the FreeBSD port to 1.0.0 release.  Thanks!

[1] https://pkg.go.dev/github.com/octeep/wireproxy?tab=versions
[2] https://www.freshports.org/net/wireproxy
[3] https://docs.freebsd.org/en/books/porters-handbook/special/index.html#using-go

**Comment by octeep** [comment]
Fixed. I'm still new to the Golang ecosystem so I didn't know about this. How long does it take for it to get `v.1.0.0` to be shown on pkg.go.dev?

**Comment by lwhsu** [comment]
Thanks!
