### ISSUE TITLE
Hey you seems forget to add me for contributors list

### ISSUE THREAD

**Issue by misakano7545** [octeep/wireproxy#31]
![7C40595F-52A9-44EC-BA7B-95546BCE0FA0](https://user-images.githubusercontent.com/96560028/161382342-ae5e6fba-1b66-4a23-bee7-7c5ddae45fea.jpeg)

![E5ECF894-56FE-4A65-83CC-213B9F3B4FEA](https://user-images.githubusercontent.com/96560028/161382345-87f7d758-d178-401c-b3d3-c3c7d702b89d.png)

![6576CEB0-8674-4E92-9DAE-B65E1A7EE31E](https://user-images.githubusercontent.com/96560028/161382371-f7ba120f-7249-457b-98e3-9e5bf81a687c.jpeg)

**Comment by octeep** [comment]
For some reasons GitHub didn't add you and @gitv2ray automatically. I've manually added you both as contributors in the release note. Thanks for pointing this out to me.
