### ISSUE TITLE
one and only one [Interface] is expected

### ISSUE THREAD

**Issue by mirrormirage0** [octeep/wireproxy#35]
Managed to get it up and running on Debian bullseye with no issues.

However , on Macbook Pro M1 (arm64), using the same conf file,  I am getting this error 
`one and only one [Interface] is expected`

Any suggestions for troubleshooting?

**Comment by octeep** [comment]
Odd, this error should only occur when you have 2 [Interface]s in your config. Do you have an example config that can reproduce the problem?

**Comment by mirrormirage0** [comment]
I used the same config file on both Debian Linux and M1 Mac.


`
# SelfSecretKey is the secret key of your wireguard peer
SelfSecretKey = #MYSECRETKEY
# SelfEndpoint is the IP of your wireguard peer
SelfEndpoint = 10.13.13.6 #From peer.conf file on wireguard server
# PeerPublicKey is the public key of the wireguard server you want to connec to
PeerPublicKey = #MYPEERPUBLICKEY
# PeerEndpoint is the endpoint of the wireguard server you want to connec to
PeerEndpoint = #MYSERVERIP:MYPORT
# DNS is the nameservers that will be used by wireproxy.
# Multple nameservers can be specified as such: DNS = 1.1.1.1, 1.0.0.1
DNS = 10.13.13.1
# KeepAlive is the persistent keep alive interval of the wireguard device
# usually not needed
# KeepAlive = 25
# PreSharedKey is the pre shared key of your wireguard device
# if you don't know what this is you don't need it
# PreSharedKey = #DONTNEEDTHIS
# TCPClientTunnel is a tunnel listening on your machine, and
# forward any TCP traffic received to the specified target via wireguard
# some applications on your LAN -> 127.0.0.1:25565 --wireguard--> play.cubecraft.net:25565
#[TCPClientTunnel]
#BindAddress = 127.0.0.1:25565
#Target = play.cubecraft.net:25565

# TCPServerTunnel is a tunnel listening on wireguard, and
# forward any TCP traffic received to the specified target via local network
# some applications on your wireguard network --wireguard--> 172.16.31.2:3422 -> localhost:25545
#[TCPServerTunnel]
#ListenPort = 3422
#Target = localhost:25545

# Socks5 create a socks5 proxy on your LAN, and any traffic would be routed via wireguard
[Socks5]
BindAddress = 127.0.0.1:25344
`

**Comment by mirrormirage0** [comment]
I figured out that this was because I was using an older version of the wireproxy config format.
After updating my config file to match the new format (having the [interface] tag, all works fine, and as expected.

The following config works fine for me.

```
[Interface]
Address = 10.13.13.6/32 
PrivateKey = #MYPRIVATEKEY 
DNS = 10.13.13.1 

[Peer]
PublicKey = #MYPUBLICKEY
Endpoint = #MYSERVER:MYPORT

# Socks5 create a socks5 proxy on your LAN, and any traffic would be routed via wireguard
[Socks5]
BindAddress = 0.0.0.0:25344
```
