### ISSUE TITLE
SelfEndpoint IP Subnet other than /24

### ISSUE THREAD

**Issue by kls0e** [octeep/wireproxy#7]
Many thanks! I was wondering about how to form a config entry for a `SelfEndpoint` ip address that resides in a different subnet than `/24`.

**Comment by octeep** [comment]
Not sure what you mean here. The `SelfEndpoint` is a static address that will be used inside the wireguard network to communicate inside the wireguard network. So I guess just set the `SelfEndpoint` to an address that resides in your subnet (the equivalent Allowed IPs of a [Device] in a wireguard config)?

**Comment by kls0e** [comment]
worked! thanks for your help.
